/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Voting {
      
    export type ProposalStruct = {id: BigNumberish, title: string, description: string, creator: AddressLike, createdAt: BigNumberish, deadline: BigNumberish, yesVotes: BigNumberish, noVotes: BigNumberish, exists: boolean, active: boolean}

    export type ProposalStructOutput = [id: bigint, title: string, description: string, creator: string, createdAt: bigint, deadline: bigint, yesVotes: bigint, noVotes: bigint, exists: boolean, active: boolean] & {id: bigint, title: string, description: string, creator: string, createdAt: bigint, deadline: bigint, yesVotes: bigint, noVotes: bigint, exists: boolean, active: boolean }
  
    }

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "createProposal" | "getAllProposals" | "getProposal" | "hasVoted" | "proposalCount" | "proposals" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProposalCreated" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'createProposal', values: [string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllProposals', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'createProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllProposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace ProposalCreatedEvent {
      export type InputTuple = [id: BigNumberish, title: string, creator: AddressLike, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, title: string, creator: string, deadline: bigint];
      export interface OutputObject {id: bigint, title: string, creator: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [proposalId: BigNumberish, voter: AddressLike, vote: boolean];
      export type OutputTuple = [proposalId: bigint, voter: string, vote: boolean];
      export interface OutputObject {proposalId: bigint, voter: string, vote: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createProposal: TypedContractMethod<
      [_title: string, _description: string, _durationInMinutes: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllProposals: TypedContractMethod<
      [],
      [Voting.ProposalStructOutput[]],
      'view'
    >
    

    
    getProposal: TypedContractMethod<
      [_proposalId: BigNumberish, ],
      [Voting.ProposalStructOutput],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    proposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {id: bigint, title: string, description: string, creator: string, createdAt: bigint, deadline: bigint, yesVotes: bigint, noVotes: bigint, exists: boolean, active: boolean }],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [_proposalId: BigNumberish, _voteYes: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createProposal'): TypedContractMethod<
      [_title: string, _description: string, _durationInMinutes: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllProposals'): TypedContractMethod<
      [],
      [Voting.ProposalStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [_proposalId: BigNumberish, ],
      [Voting.ProposalStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {id: bigint, title: string, description: string, creator: string, createdAt: bigint, deadline: bigint, yesVotes: bigint, noVotes: bigint, exists: boolean, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_proposalId: BigNumberish, _voteYes: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'ProposalCreated(uint256,string,address,uint256)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'VoteCast(uint256,address,bool)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }