/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { PayableOverrides } from "../common.js"
  import type { Lock, LockInterface } from "../Lock.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_unlockTime",
        "type": "uint256"
      }
    ],
    "stateMutability": "payable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "when",
        "type": "uint256"
      }
    ],
    "name": "Withdrawal",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address payable",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "unlockTime",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080601f61028338819003918201601f19168301916001600160401b0383118484101760b75780849260209460405283398101031260b35751804210156062575f55600180546001600160a01b031916331790556040516101b790816100cc8239f35b60405162461bcd60e51b815260206004820152602360248201527f556e6c6f636b2074696d652073686f756c6420626520696e207468652066757460448201526275726560e81b6064820152608490fd5b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015610012575f80fd5b5f3560e01c908163251c1aa314610191575080633ccfd60b1461007457638da5cb5b1461003d575f80fd5b34610070575f36600319011261007057602073ffffffffffffffffffffffffffffffffffffffff60015416604051908152f35b5f80fd5b34610070575f366003190112610070575f54421061014c5773ffffffffffffffffffffffffffffffffffffffff60015416803303610107575f808080937fbf2ed60bd5b5965d685680c01195c9514e4382e28e3a5a2d2d5244bf59411b936040478151908152426020820152a147908282156100fe575bf1156100f357005b6040513d5f823e3d90fd5b506108fc6100eb565b60405162461bcd60e51b815260206004820152601460248201527f596f75206172656e277420746865206f776e65720000000000000000000000006044820152606490fd5b60405162461bcd60e51b815260206004820152601660248201527f596f752063616e277420776974686472617720796574000000000000000000006044820152606490fd5b34610070575f366003190112610070576020905f548152f3fea164736f6c634300081c000a";

  
      type LockConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LockConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Lock__factory extends ContractFactory {
    
      constructor(...args: LockConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_unlockTime: BigNumberish, overrides?: PayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_unlockTime, overrides || {});
    };
    override deploy(_unlockTime: BigNumberish, overrides?: PayableOverrides & { from?: string }) {
      return super.deploy(_unlockTime, overrides || {}) as Promise<Lock & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Lock__factory {
      return super.connect(runner) as Lock__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LockInterface {
      return new Interface(_abi) as LockInterface;
    }
    
    override attach(address: string | Addressable): Lock {
      return super.attach(address) as Lock;
    }
  static connect(address: string, runner?: ContractRunner | null): Lock {
      return new Contract(address, _abi, runner) as unknown as Lock;
    }
  }

  
  